# Generated by Django 6.0.1 on 2026-03-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.TextField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('search_info', models.TextField(blank=True, null=True)),
                ('authors', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('reviews', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
