server{
    listen 80;
    server_name localhost 192.168.1.7;

    location /images/ {
        root /usr/share/nginx/html; 
        autoindex on;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}